paths:
  /api/products/:
    get:
      summary: Trae todos los productos disponibles en la aplicacion.
      tags:
        - Products
      responses:
        "200":
          description: La operacion fue exitosa!!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        "400": 
          description: Se envió un dato no esperado.
        "500":
          description: Error inesperado en el servidor, no se pudo manejar el proceso.



components:
  schemas:
    Products: 
      type: object
      properties:
        _id: 
          type: ObjectId
          description: Id autogenerado de MongoDB.
        code: 
          type: String
          description: codigo del producto
        title:
          type: String
          description: Titulo del producto
        description:
          type: String
          description: descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock disponible del producto
        category:
          type: String
          description: Categoria del producto 
      example: 
        _id: ObjectId("644f032238d2951176a9c699")
        code: "123aaa"
        title: "caperucita"
        description: "Caperucita y el lobo"
        price: 9200
        stock: 30
        category: "Cuento"
 